# -*- coding: utf-8 -*-
"""OnlineFraudDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DNdwl7gL17aPkvlBUPjLJEuJitnrrx_
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv("/content/onlinefraud.csv")

print(data.head())

data = data.drop(['nameOrig', 'nameDest'], axis=1)

data['type'] = data['type'].astype('category').cat.codes

X = data.drop(['isFraud'], axis=1)
y = data['isFraud']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(y_train.isnull().sum())
print(y_test.isnull().sum())
y_train = y_train.fillna(0)
y_test = y_test.fillna(0)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division = 1))